# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 013368436c88822c926dd7c01243cb58317120595b65c0dd3ea91d0ff64275dd767045885b797a014b7664bb915b6f364f84de80a047dc1ac88f320bee02fc44

test:
  secret_key_base: 8112560380d27580ca7070899fcc87cdc01053590aee46265deba9739e848a5bddf2625c911ecfafdf86f5a76cc84a20bdae461c7a690990512114d22622cb3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
